### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by qzzqzzb** [zaixizhang/graphbackdoor#1]
Hi authors,

I runned the code as instructed, and I got
```
FileNotFoundError: [Errno 2] No such file or directory: 'subgraph_gen/ER_bitcoin_triggersize_3_prob_0.8.edgelist'
```

It seems like there are something missed in dataset.zip? The unziped folder contains four datasets each of which has a single txt file.

Any insights?

**Comment by Guo-lab** [comment]
> Hi authors,
> 
> I runned the code as instructed, and I got
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'subgraph_gen/ER_bitcoin_triggersize_3_prob_0.8.edgelist'
> ```
> 
> It seems like there are something missed in dataset.zip? The unziped folder contains four datasets each of which has a single txt file.
> 
> Any insights?

The subgraph_gen should be created by self at root directory.

**Comment by zaixizhang** [comment]
It seems the issue has been addressed. Thanks for your feedback!
